INSERT INTO books  (title, publicationevent, description, image, category) VALUES
('La comunidad del anillo', '1954-07-29', 'Es el primer libro de la trilogía del señor de los anillos. Contiene 576 páginas, pero una vez que empiezas a leerlo se te hace muy ameno. La calidad de la historia que representa Tolkien, creando todo un nuevo mundo, es sin duda sobresaliente. De hecho, actualmente ha tenido muchas influencias tanto en novelas como en videojuegos o películas. El relato comienza con el cumpleaños de Bilbo Bolsón, justo después Frodo hereda el anillo único. Gandalf al conocer de que se trata del anillo único le encomienda a Frodo de destruirlo. Tendrán por tanto que atravesar prácticamente toda la tierra media, ya que el anillo solo puede ser roto en el monte del destino en Mordor donde reside Sauron. Para ello, se enfrentarán a numerosos peligros, incluyendo orcos, trolls, arañas gigantes y espectros. Este libro es muy recomendado si te interesa el género de la fantasía o fantástica.', 'la_comunidad_del_anillo.jpeg', "the-lord-of-the-rings"),
('Las dos torres', '1954-11-11', 'El segundo libro de la trilogía. Continuando la magnifica historia de la comunidad del anillo. Las dos torres se caracteriza por una redacción más oscura y sombría. Sigue teniendo la calidad del primer libro. Contiene 408 páginas, siendo más corto que el primero. Este segundo volumen se separa la comunidad del anillo pero esto no impide que continue el viaje. Tendrán que seguir avanzando por la tierra media.', 'las_dos_torres.jpeg', "the-lord-of-the-rings"),
('El retorno del rey', '1955-10-20', 'Con este libro concluye la trilogía del señor de los anillos. Titulada el retorno del rey. El título hace referencia al regreso de Aragorn como rey de Gondor. Tiene una historia épica como así también más esperanzadora y redentora. Trasladándose en varios escenarios con multitud de detalles. Minas Tirith luce espectacular gracias a la descripción precisa que hace Tolkien. Finalmente, el anillo único queda destruido, se suceden varias batallas, cabe destacar la de minas tirith y también la que se desarrolla en la puerta negra, la entrada a Mordor. De esta manera regresa la paz y la prosperidad a la tierra media.', 'el_retorno_del_rey.jpeg' , "the-lord-of-the-rings"),
('El Hobbit', '1937-09-21', 'Aquí empieza toda la historia de la tierra media ya que con este relato comienza la saga. Se lanzó antes que el señor de los anillos y en un principio fue un libro para sus hijos pequeños. De todas formas, Tolkien envió el manuscrito a varias personas, finalmente se publicó a manos de la editorial George Allen & Unwin. La historia comienza con bilbo bolsón el cual se embarcará en una aventura para recuperar el tesoro que está protegido por un dragón en la montaña solitaria', 'el_hobbit.jpeg' , "la_tierra_media"),
('El Silmarillion', '1977-09-15', 'Es una recopilación de obras de Tolkien, aunque no la publicó Tolkien sino su hijo Christopher Tolkien, en el año 1977. En esta obra se cita la creación de Eä y el surgimiento de las razas más importantes (Valar, Maiar, elfos, hombres y enanos) de Arda. El mayor fragmento del Silmarillion es titulado «Quenta Silmarillion». En él se compone la historia de la primera edad del sol en la tierra media. La última historia («De los Anillos de Poder y la Tercera Edad») sirve como marco de referencia histórico para El hobbit y El Señor de los Anillos que son las novelas más populares de Tolkien.', 'el_silmarillion.jpeg' , "la_tierra_media"),
('Cuentos desde el reino peligroso', '1997-01-01', 'Básicamente se trata de una antología que engloba algunas de las obras menos conocidas de Tolkien. Publicada en 1997 por HarperCollins sin ilustraciones, fue publicada posteriormente con una edición expandida en 2008, esta vez las ilustraciones se llevaron a cabo por Alan Lee. Asimismo, está edición también se introduce por Thomas Shippey. Las obras en la edición del 2008 integra las siguientes obras: Roverandom, Egidio, el granjero de Ham, Las aventuras de Tom Bombadil, El herrero de Wootton Major, Hoja, de Niggle y Sobre los cuentos de hadas.', 'cuentos.jpeg' , "la_tierra_media")

INSERT INTO films  (title, publicationevent, video, image) VALUES
('La comunidad del anillo', '1954-07-29', 'https://www.youtube.com/embed/iFOucwxKRFE?si=ZEaeWRzf8hej0YhC', 'pelicula_la_comunidad_del_anillo_3.jpeg'),
('Las dos torres', '1954-11-11', 'https://www.youtube.com/embed/f9W1l7E5bHg?si=BF7QtaZJpz7_HmdD', 'pelicula_las_dos_torres_2.jpeg'),
('El retorno del rey', '1955-10-20', 'https://www.youtube.com/embed/pYo4Gj5vq9o?si=iiRurRRC8az1mo-C', 'pelicula_el_retorno_del_rey_3.jpeg'),
('El Hobbit', '1937-09-21', 'https://www.youtube.com/embed/sI8OQRXhcZE?si=cY2WJqJ-PIJys6sz', 'hobbit.jpeg'),
('El Hobbit 2', '1937-09-21', 'https://www.youtube.com/embed/X3UJolXeC98?si=-j6-SW6ydjoWEUJG', 'hobbit-2.jpeg'),
('El Hobbit 3', '1937-09-21', 'https://www.youtube.com/embed/L-jb4GtXyKY?si=WStSaNT1vZv_wj-Q', 'hobbit-3.jpeg')

INSERT INTO videogame  (title, publicationevent, description, image, genre) VALUES
('El Señor de los Anillos: La Batalla por la Tierra Media 2', '2006-02-28', 'La batalla por la tierra media 2 es la continuación del juego de estrategia en tiempo real inspirado de la obra de Tolkien, el señor de los anillos. Esta secuela incluye tres nuevas facciones: los enanos, los elfos y los trasgos, formando de esta manera un total de seis razas para jugar. Además de una campaña épica compuesta por la campaña del bien y del mal, incluye también varios modos de juego y la opción de jugar en línea o en red local.', 'videojuego1.jpeg', 'estrategia en tiempo real'),
('El Señor de los Anillos: La Batalla por la Tierra Media 2: The Rise of the Witch King', '2006-11-29', 'Es la expansión del videojuego (El Señor de los Anillos: La Batalla por la Tierra Media 2). Figura una nueva facción llamada Angmar. También dispone de una campaña totalmente nueva donde controlaremos al rey brujo y a sus ejércitos, más mapas y demás mejoras para una experiencia de juego agradable.', 'videojuego2.jpeg', 'estrategia en tiempo real'),
('El Señor de los Anillos Online: Riders of Rohan', '2012-10-15', 'Desarrollado por Turbine Entertainment y editado por Warner Bros. Interactive Entertainment, es un videojuego multijugador online. Concretamente esta edición es una expansión del señor de los anillos online. Las novedades esta entrega es que incorpora el combate a caballo y también permite a los jugadores a unirse a los Rohirrim y pasear a través de los extensos Llanos Orientales de Rohan.', 'videojuego3.jpeg', 'Multijugador Online'),
('El Señor de los Anillos: Las aventuras de Aragorn', '2010-10-29', 'Este videojuego de acción protagonizado por el emblemático personaje del señor de los anillos: Aragorn. En él conoceremos más acerca de su historia y recordaremos escenarios inspiradas en las películas. En conclusión, es un videojuego recomendado para los amantes del señor de los anillos y los que no lo son y quieren tomar contacto; a pesar de la baja dificultad y algunos errores de control.', 'videojuego4.jpeg', 'Aventura de acción'),
('La Tierra Media: Sombras de Mordor', '2014-09-30', 'Este videojuego, su genero es de rol y acción y la cámara es en tercera persona. Ha sido desarrollado por Monolith Productions y distribuido por Warner Bros. Interactive Entertainment para Windows, xbox 360, xbox one, playstation 3 y playstation 4. Este título se sitúa entre la historia del hobbit y el señor de los anillos. En cuanto a los apartados gráficos son con un nivel de detalle asombroso.', 'videojuego5.jpeg', 'Hack and Slash'),
('LEGO: El Hobbit', '2014-04-11', 'Lego: el hobbit, como su nombre indica está basado en los populares juguetes de lego. Es un videojuego enfocado para toda la familia. Se ambienta en las películas del Hobbit producidas y dirigidas por Peter Jackson, que a su vez se basan en el libro de Tolkien. Podremos manejar a diferentes personajes como Bilbo, Gandalf, etc. Para concluir la historia al llegar a la montaña solitaria donde les espera el poderoso dragón Smaug.', 'videojuego6-2.jpeg', 'Aventura de acción')